language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
install:
 - pip install flake8
 - pip install -r reqs/full-py${TRAVIS_PYTHON_VERSION%.*}.txt
script:
 #- flake8 `find . -iname "*.py" -not -ipath "*migration*"`
 - ./runtests.sh
