language: python
python:
  - 2.7
  - 3.6
sudo: false
matrix:
  include:
    - python: 2.7
      script: tox -e docs
    - python: 2.7
      script: tox -e lint
    - python: 2.7
      script: tox -e eslint
script:
  - tox
cache:
  directories:
    - ~/.cache/pip
    - ~/.nvm/nvm.sh
install:
  - pip install tox-travis
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install --lts
  - nvm use --lts
  - npm install
  - bower install
script:
  - tox
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#random
    on_success: change
    on_failure: always
